# permissions for end users to view pushscreeners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pushscreener-viewer-role
rules:
- apiGroups:
  - github.screeners.kuberik.io
  resources:
  - pushscreeners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.screeners.kuberik.io
  resources:
  - pushscreeners/status
  verbs:
  - get
