
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.kuberik.io
  resources:
  - screeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kuberik.io
  resources:
  - screeners/status
  verbs:
  - get
  - patch
  - update
