# permissions for end users to edit screeners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: screener-editor-role
rules:
- apiGroups:
  - core.kuberik.io
  resources:
  - screeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kuberik.io
  resources:
  - screeners/status
  verbs:
  - get
