apiVersion: core.kuberik.io/v1alpha1
kind: Screener
metadata:
  name: push-screener
spec:
  movie: kuberik-ci
  class:
    name: screeners.kuberik.io/github
    type: Push
  config:
    repo:
      owner: kuberik
      name: kuberik
